version: "3"


networks:
  kafka-network:
    driver: bridge
  cassandra-network:
    driver: bridge


services:
# Kafka broker 
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 32967:32967
      - 9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181,PLAINTEXT_HOST://:32967
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:32967
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@//:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - ./kafka:/bitnami/kafka:latest
    networks:
      - kafka-network
      - cassandra-network

# Kafka UI
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8080:8080'
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - kafka-network
      - cassandra-network

# Template for Flink jobmanager and taskmanager: 
# https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/deployment/resource-providers/standalone/docker/#using-flink-python-on-docker

# Flink jobmanager
  jobmanager:
    image: pyflink:latest
    container_name: jobmanager-1
    volumes:
    - ./connectors/flink-sql-connector-kafka-3.0.2-1.18.jar:/opt/flink/usrlib/flink-sql-connector-kafka-3.0.2-1.18.jar
    # User's pyflink jobs
    - ./usrlib:/opt/flink/usrlib
    
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - kafka-network
        


# Flink taskmanager
  taskmanager:
    image: pyflink:latest
    container_name: taskmanager-1
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - kafka-network
  

# Cassandra 
  cassandra:
    image: cassandra:4.1.4
    # ports:
    #   - "9042:9042"
    container_name: cassandra
    hostname: cassandra
    networks:
      - cassandra-network

# Python producer
  python-producer:
    image: python:3.10-usrlib-as-workdir
    container_name: python-producer
    volumes: 
      - ./usrlib/producer.py:/usrlib/producer.py
      - ./helpers/getting-started.ini:/helpers/getting-started.ini
      - ./github-data:/github-data
    command: ['python', '/usrlib/producer.py', '/helpers/getting-started.ini']
    depends_on:
      - kafka
    networks:
      - kafka-network
      - cassandra-network

# Python consumer
  python-consumer:
    image: python:3.10-usrlib-as-workdir
    container_name: python-consumer
    volumes: 
      - ./usrlib/getting-started.ini:/usrlib/getting-started.ini
      - ./usrlib/consumer.py:/usrlib/consumer.py
      - ./github-data:/github-data
    command: ['python', '/usrlib/consumer.py', 'helpers/getting-started.ini']
    depends_on:
      - kafka
      - cassandra
    networks:
      - cassandra-network

      