version: '3'

networks:
  cassandra-network:
    driver: bridge

services:
# Kafka broker
  kafka:
    image: bitnami/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - '9092:9092'
      - '2181:2181'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - ./kafka:/bitnami/kafka:latest
    networks:
      - cassandra-network

# Kafka UI
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8080:8080'
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    volumes:
      - ./kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - cassandra-network
      
# Cassandra 
  cassandra:
    image: cassandra:4.1.4
    # ports:
    #   - "9042:9042"
    container_name: cassandra
    hostname: cassandra
    networks:
      - cassandra-network

# Python producer
  python-producer:
    image: python:3.10-script-executing-image
    container_name: python-producer
    volumes: 
      - ./python-scripts/producer.py:/producer.py
      - ./helpers/getting-started.ini:/helpers/getting-started.ini
      - ./github-data:/github-data
    command: ['python', 'python-scripts/producer.py', 'helpers/getting-started.ini']
    depends_on:
      - kafka
    networks:
      - cassandra-network

# Python consumer
  python-consumer:
    image: python:3.10-script-executing-image
    container_name: python-consumer
    volumes: 
      - ./helpers/getting-started.ini:/helpers/getting-started.ini
      - ./python-scripts/consumer.py:/python-scripts/consumer.py
      - ./github-data:/github-data
    command: ['python', 'python-scripts/consumer.py', 'helpers/getting-started.ini']
    depends_on:
      - kafka
      - cassandra
    networks:
      - cassandra-network









