networks:
  data-network:
    name: data-network
    driver: bridge

# To compose from a docker-compose-get-metrics-services.yaml:
# docker compose -f docker-compose-get-metrics-services.yaml run cassandra_stelios cassandra-ui (or other service)


services:

  # Get the decompressed sizes of compressed files
  python-get-decompressed-size-of-downloaded-file:
    image: python:3.10-script-executing-image-with-requests_sse
    # image: python:3.10-script-executing-image
    container_name: python-get-decompressed-size-of-downloaded-file
    volumes: 
      - ./usrlib/test_scripts/get_decompressed_size_of_downloaded_file.py:/usrlib/get_decompressed_size_of_downloaded_file.py
      
      - ./usrlib/github_data:/github_data
      - ./usrlib/test_scripts:/test_scripts
    
    
    command: ['python', 'get_decompressed_size_of_downloaded_file.py']
    environment:
      - PYTHONUNBUFFERED=1
    

  # Get the number of lines in files
  python-get-number-of-lines-in-downloaded-files:
    image: python:3.10-script-executing-image-with-requests_sse
    # image: python:3.10-script-executing-image
    container_name: python-get-number-of-lines-in-downloaded-files
    volumes: 
      - ./usrlib/test_scripts/get_num_of_lines_of_compressed_file.py:/usrlib/get_num_of_lines_of_compressed_file.py
      
      - ./usrlib/github_data:/github_data
      - ./usrlib/test_scripts:/test_scripts
    
    
    command: ['python', 'get_num_of_lines_of_compressed_file.py']
    environment:
      - PYTHONUNBUFFERED=1
  


  # Cassandra 
  cassandra_stelios:
    image: cassandra:4.1.7
    ports:
      - "9142:9142"
    container_name: cassandra_stelios
    hostname: cassandra_stelios
    volumes:
      - /var/lib/cassandra:/var/lib/cassandra
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - data-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh cassandra_stelios 9142 -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Cassandra UI
  cassandra-ui:
      image: ipushc/cassandra-web
      container_name: cassandra-ui
      ports:
        - "8083:8083"
      depends_on:
        cassandra_stelios:
          condition: service_healthy
      networks:
        - data-network
      environment: 
        - CASSANDRA_HOST=cassandra_stelios
        - CASSANDRA_PORT=9142

  # Get number of accepted pull requests for all dates from Cassandra
  get-accepted-pull-requests-from-cassandra:
    image:  python:3.10-script-executing-image-with-requests_sse
    container_name: get-accepted-pull-requests-from-Cassandra
    volumes: 
      - ./usrlib/test_scripts/get_avg_accepted_PR_rates_2024_12.py:/usrlib/get_avg_accepted_PR_rates_2024_12.py
      - ./usrlib/test_scripts:/test_scripts
    networks:
      - data-network
    depends_on:
      cassandra_stelios:
        condition: service_healthy

    command: ['python', 'get_avg_accepted_PR_rates_2024_12.py']
    environment:
      - PYTHONUNBUFFERED=1
  
    
